### PR TITLE
Options to control lines before/after

### PR DESCRIPTION
**Pull request by JairoMartinezA**
Hi Alex,

Consider the next change on this plugin to control basically the grep functionality to include lines before/after the matches:

image

File used to test the new options:
[Duplicates.zip](https://github.com/CudaText-addons/cuda_extract_strings/files/6750499/Duplicates.zip)

### CODE REVIEW

**Comment by Alexey-T** [comment]
~~first please tell what are these options?~~

- include line numbers
- keep lexer
- number of lines 1/2 

cannot guess.
@halfbrained @miroslavmatas maybe you are interested.

**Comment by Alexey-T** [comment]
ah, found it,
```
+ add: option to include line numbers in the "Filter Lines" dialog
+ add: option to preserve the current lexer in the "Filter Lines" dialog
+ add: option to include a number of lines before or after the matched line in
  the "Filter Lines" dialog
```
I will test it.

**Comment by MiroslavMatas** [comment]
https://user-images.githubusercontent.com/42316770/124226837-02ea5680-db0a-11eb-8df6-3ea9facfbc41.mp4

Find in Files is able to "link" or "connect" results to source lines…
will be possible to implement the same also for "Filter Lines"?
/like: can see result at new tab… double click and go to source line… or context menu like on mentioned plugin…/

**Comment by JairoMartinezA** [comment]
Hi Alex,

I think current editor functionality is no able to do what @MiroslavMatas request, for that I think is necessary to use a listbox or some object to create the "link" to the file but not just and "editor" control, I was also thinking in _cuda_embed_ed_ but for that the results need to be parser like an XML or put directly the link to file using: _file://path_etc_, right?

**Comment by Alexey-T** [comment]
yes, right, plain editor cannot have links. FindInFiles does its links via memory data, and its editors are read-only.

**Comment by MiroslavMatas** [comment]
can see it now… you are correct
please forget for this idea, it is ok
appreciate suggested enhancements

**Pull request merged**
